version: "3.9"

services:
  app: #the name of the service that will run our Dockerfile
    build:
      context: .  #we wanna build the Dockerfile inside our current directory
      args:
        - DEV=true #using only for DEVELOPMENT part --> build an argument DEV and set it True
    ports:
      - "8000:8000" #maps our local port 8000 to port 8000 inside our Docker container
    volumes:
      - ./app:/app #map the /app directory that we created to /app inside our container
    command: > #used to run the service 
      sh -c "python manage.py runserver 0.0.0.0:8000"
      
    #this would tell our app HOW TO CONNECT to the DB
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme

    #the app service depends on the DB service to start
    depends_on:
      - db

  #start another service for DB (Postgres-SQL)
  db:
    #Postgres image from hub.docker.com
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
    #just setting env variables to Postgres DB to create dev credentials for the
    #local development
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
    
    
volumes:
  dev-db-data:
  